spring:
  profiles:
    active: pro
  thymeleaf:
    cache: true
  jpa:
    open-in-view: false
  session:
    store-type: redis
    timeout: 7200
  data:
    redis:
      repositories:
        enabled: false
    ## 静态资源的浏览器缓存设置
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /*
project:
  project-name: temp-boot
  develop-name:
  develop-url: http://www.miskss.com
  version: 1.0.0
server:
  port: 8088
