spring:
  profiles:
    active: pro
  thymeleaf:
    cache: true
  ## 静态资源的浏览器缓存设置
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  jpa:
    open-in-view: false
  session:
    store-type: redis
    timeout: 7200
  data:
    redis:
      repositories:
        enabled: false
project:
  project-name: temp-boot
  develop-name: 南京途酷科技有限公司
  develop-url: http://www.tklvyou.cn
  version: 1.0.0
server:
  port: 8088
